Edit organization public info
rarimo/rarime-app pull request #31
Opened 2024-01-25 17:44 UTC by ardier16

2024-01-29 15:14 UTC, lukachi requested changes

2024-01-29 15:14 UTC, lukachi commented on src/pages/Orgs/pages/OrgsId/pages/OrgRoot/components/EditLinksDrawer.tsx
> +import { useOrgDetails } from '../../../hooks'
alias

2024-02-02 11:35 UTC, lukachi approved these changes
lgtm

2024-02-02 11:57 UTC, WhiteNik16 approved these changes

2024-02-02 11:58 UTC, merged