global contexts restructurization
rarimo/rarime-app pull request #8
Opened 2023-12-28 20:54 UTC by lukachi

2023-12-28 20:55 UTC, lukachi commented
Seems like every Web3 or Auth or Snap, ...etc contexts in `main.ts` could rerender router provider

2023-12-28 21:25 UTC, ardier16 commented on src/contexts/auth.tsx
> +  }, [])
IMO we don't need this wrapper and useCallback at all

we can use `authStore.setJwt` directly as it's defined outside of the React scope

2023-12-28 21:25 UTC, ardier16 commented on src/contexts/auth.tsx
> +    //Todo: add real logic
```suggestion
    // TODO: add implementation
```

2023-12-28 21:25 UTC, ardier16 commented on src/routes.tsx
> +  if (!isAppInitialized) return null
we displayed a loader before

2023-12-29 11:17 UTC, ardier16 requested changes

2023-12-29 11:17 UTC, ardier16 commented on src/pages/SignIn.tsx
> +      // navigate(RoutePaths.Orgs)
remove comments

2023-12-29 11:27 UTC, ardier16 approved these changes

2023-12-29 11:42 UTC, merged